#!/bin/bash
# Helper script for downloading and setting up example data
# Note: This is a template - users should adapt based on their data sources

echo "================================================================"
echo "InstantPose - Example Data Setup"
echo "================================================================"
echo ""
echo "This script helps you set up the LINEMOD/OCCLUSION_LINEMOD datasets."
echo ""
echo "LINEMOD Dataset:"
echo "  - Download from: http://ptak.felk.cvut.cz/6DB/public/datasets/hinterstoisser/"
echo "  - Or: BOP Challenge website (https://bop.felk.cvut.cz/datasets/)"
echo ""
echo "OCCLUSION_LINEMOD Dataset:"
echo "  - Download from: https://bop.felk.cvut.cz/datasets/"
echo "  - Look for 'LM-O' (LINEMOD Occluded)"
echo ""
echo "Directory Structure:"
echo "  OCCLUSION_LINEMOD/"
echo "    RGB-D/"
echo "      color_*.png"
echo "      depth_*.png"
echo "    poses/"
echo "      pose*.txt"
echo "    models/"
echo "      obj_*.ply"
echo ""
echo "Reconstructed Meshes:"
echo "  - Use InstantMesh or similar LRM to reconstruct object meshes"
echo "  - Place reconstructed meshes in: assets/recon_meshes/"
echo "  - Name format: <object_name>.obj or <object_name>.ply"
echo "  - Supported objects: ape, benchvise, cam, can, cat, driller, duck, eggbox, glue, holepuncher, iron, lamp, phone"
echo ""
echo "Example Symlink (Linux/Mac):"
echo "  ln -s /path/to/OCCLUSION_LINEMOD ./OCCLUSION_LINEMOD"
echo ""
echo "Example Symlink (Windows PowerShell):"
echo "  New-Item -ItemType SymbolicLink -Path OCCLUSION_LINEMOD -Target C:\path\to\OCCLUSION_LINEMOD"
echo ""
echo "================================================================"

